highlighter: pygments
url: http://tpolecat.github.io/
# lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: redcarpet

collections:
  doobie-0.2.0:
    output: true
    title: "book of doobie"
    index: "00-index.html"
    version: "0.2.0"
  doobie-0.2.1:
    output: true
    title: "book of doobie"
    index: "00-index.html"
    version: "0.2.1"
  doobie-0.2.2:
    output: true
    title: "book of doobie"
    index: "00-index.html"
    version: "0.2.2"
